#! /bin/sh

# chkconfig: 016 20 95
# description: Stops ourgrid-aggregator
# processname: aggregator-stop

### BEGIN INIT INFO
# Provides:          aggregator
# Required-Stop:     $remote_fs $syslog
# Default-Stop:      0 1 6
# Short-Description: Stops the aggregator module of OurGrid(ourgrid.org)
### END INIT INFO

#sudo -u ourgrid /usr/bin/aggregator stop
su ourgrid -c "aggregator stop" &> /dev/null