#!/bin/bash -e
# Source debconf library.

recommended=$(grep -c processor /proc/cpuinfo)

NUM_WORKERS=$recommended
USERNAME=$(hostname)
SERVERNAME="xmpp.ourgrid.org"
PASSWORD="xmpp-password"
PEERADDRESS="peer-lsd@xmpp.ourgrid.org"
IDLENESS_DETECTOR="yes"
IDLENESS_TIME="1200"

/bin/bash copyworkers "$NUM_WORKERS" "$USERNAME" "$SERVERNAME" "$PASSWORD" "$PEERADDRESS" "$IDLENESS_DETECTOR" "$IDLENESS_TIME"

if [ -z "$(grep "xhost +si:localuser:ourgrid" /etc/profile)" ]; then 
	echo "xhost +si:localuser:ourgrid" >> /etc/profile
fi	

CPU_ARCH=`uname -m`
CPU_x86_64_ARCH=x86_64
tar -xvf /etc/ourgrid/xprintidle.tar.gz -C /etc/ourgrid/ 
if [ $CPU_ARCH == $CPU_X86_64_ARCH ]; then 
	mv /etc/ourgrid/xprintidle-x86_64 /etc/ourgrid/bin/xprintidle
	rm /etc/ourgrid/xprintidle-i386
	rm /etc/ourgrid/xprintidle.tar.gz
	else
		mv /etc/ourgrid/xprintidle-i386 /etc/ourgrid/bin/xprintidle
		rm /etc/ourgrid/xprintidle-x86_64
		rm /etc/ourgrid/xprintidle.tar.gz
fi

chmod +x /etc/init.d/worker
su - -c "chkconfig --level 2345 worker on"
su - -c "chkconfig --level 016 worker on"

chown ourgrid /usr/bin/worker
chown ourgrid /usr/share/ourgrid
chown -R ourgrid /etc/ourgrid
touch /etc/ourgrid/idleness
chmod 777 /etc/ourgrid/idleness
chmod +x /etc/ourgrid/bin/xprintidle
chmod +x /etc/X11/Xsession.d/99ourgrid-worker-idleness


rm -f /usr/bin/copyworkers