
package org.ourgrid.broker.controlws.gatewayws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Broker3GControlWS", targetNamespace = "http://gatewayws.controlws.broker.ourgrid.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Broker3GControlWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "submitJob", targetNamespace = "http://gatewayws.controlws.broker.ourgrid.org/", className = "org.ourgrid.broker.controlws.gatewayws.client.SubmitJob")
    @ResponseWrapper(localName = "submitJobResponse", targetNamespace = "http://gatewayws.controlws.broker.ourgrid.org/", className = "org.ourgrid.broker.controlws.gatewayws.client.SubmitJobResponse")
    public int submitJob(
        @WebParam(name = "arg0", targetNamespace = "")
        WsJobSpec arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelJob", targetNamespace = "http://gatewayws.controlws.broker.ourgrid.org/", className = "org.ourgrid.broker.controlws.gatewayws.client.CancelJob")
    @ResponseWrapper(localName = "cancelJobResponse", targetNamespace = "http://gatewayws.controlws.broker.ourgrid.org/", className = "org.ourgrid.broker.controlws.gatewayws.client.CancelJobResponse")
    public boolean cancelJob(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cleanJob", targetNamespace = "http://gatewayws.controlws.broker.ourgrid.org/", className = "org.ourgrid.broker.controlws.gatewayws.client.CleanJob")
    @ResponseWrapper(localName = "cleanJobResponse", targetNamespace = "http://gatewayws.controlws.broker.ourgrid.org/", className = "org.ourgrid.broker.controlws.gatewayws.client.CleanJobResponse")
    public boolean cleanJob(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://gatewayws.controlws.broker.ourgrid.org/", className = "org.ourgrid.broker.controlws.gatewayws.client.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://gatewayws.controlws.broker.ourgrid.org/", className = "org.ourgrid.broker.controlws.gatewayws.client.GetStatusResponse")
    public String getStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
