
package org.ourgrid.broker.controlws.gatewayws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Broker3GControlWSService", targetNamespace = "http://gatewayws.controlws.broker.ourgrid.org/", wsdlLocation = "http://localhost:8080/broker3gcontrol/broker3gcontrol?wsdl")
public class Broker3GControlWSService
    extends Service
{

    private final static URL BROKER3GCONTROLWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.ourgrid.broker.controlws.gatewayws.client.Broker3GControlWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.ourgrid.broker.controlws.gatewayws.client.Broker3GControlWSService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/broker3gcontrol/broker3gcontrol?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/broker3gcontrol/broker3gcontrol?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BROKER3GCONTROLWSSERVICE_WSDL_LOCATION = url;
    }

    public Broker3GControlWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Broker3GControlWSService() {
        super(BROKER3GCONTROLWSSERVICE_WSDL_LOCATION, new QName("http://gatewayws.controlws.broker.ourgrid.org/", "Broker3GControlWSService"));
    }

    public Broker3GControlWSService(String webServiceUrl) throws MalformedURLException {
    	super(new URL(webServiceUrl), new QName("http://gatewayws.controlws.broker.ourgrid.org/", "Broker3GControlWSService"));
    }
    
    /**
     * 
     * @return
     *     returns Broker3GControlWS
     */
    @WebEndpoint(name = "Broker3GControlWSPort")
    public Broker3GControlWS getBroker3GControlWSPort() {
        return super.getPort(new QName("http://gatewayws.controlws.broker.ourgrid.org/", "Broker3GControlWSPort"), Broker3GControlWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Broker3GControlWS
     */
    @WebEndpoint(name = "Broker3GControlWSPort")
    public Broker3GControlWS getBroker3GControlWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://gatewayws.controlws.broker.ourgrid.org/", "Broker3GControlWSPort"), Broker3GControlWS.class, features);
    }

}
