#! /bin/sh

# chkconfig: 2345 95 20
# description: Starts ourgrid-worker
# processname: worker-start

### BEGIN INIT INFO
# Provides:          worker
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the worker module of OurGrid(ourgrid.org)
### END INIT INFO

su ourgrid -c "worker start" &> /dev/null