#!/bin/bash
# Source debconf library.
. /usr/share/debconf/confmodule

echo "Creating user \"ourgrid\"."
db_get ${package.name}/user_password
PASSWORD="$RET"

pass=$(perl -e 'print crypt($ARGV[0], "password")' $PASSWORD)
useradd -d /etc/ourgrid/home -m -s /bin/bash -p $pass ourgrid
[ $? -eq 0 ] && echo "ourgrid user has been added to system!"
	
check="ourgrid		ALL=(ALL) NOPASSWD:ALL"; [[ -n $(grep "$check" /etc/sudoers ) ]] && echo "Permission Already Exists" || echo "$check" >> /etc/sudoers

[[ -d /var/log/ourgrid ]] && chown ourgrid /var/log/ourgrid
chown -R ourgrid /usr/bin/testjvm
