#!/bin/bash

	# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	#
	# Package:		OurGrid 4.0
	#
	# Copyright (c) 2002-2006 Universidade Federal de Campina Grande 
	# 
	# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Setting macros
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
OK=0
NOK=1

# Setting error codes (from 2 to 254)
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
ERR_BASE=64
ERR_STD_MISUSE=$(($ERR_BASE))
ERR_OGROOT_NOT_DEFINED=$(($ERR_BASE+1))
ERR_JAVAOPTIONS_NOT_DEFINED=$(($ERR_BASE+2))
ERR_CLASSPATH_NOT_DEFINED=$(($ERR_BASE+3))
ERR_JAVA_NOT_FOUND=$(($ERR_BASE+4))
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

OGROOT="/etc/ourgrid/"

usage(){

if [ $# -eq 0 ]; then
	echo "Usage: worker command [command-options-and-arguments] index"
	echo "	where command is gui, start, stop, status or restart"
	echo "	where command-options-and-arguments depend on the specific command"
	echo "  where index is the number of the worker to act on [blank to act on all of them]"
	echo
	echo "For OurGrid updates and additional information, see the "
	echo "OurGrid Project home page at http://www.ourgrid.org/ "
else
	case "$1" in
		start) echo "help $1"
		;;
		stop) echo "help $1"
		;;
		status) echo "help $1"
		;;
		restart) echo "help $1"
		;;
		gui) echo "help $1"
		;;
		*) echo "not implemented" 
	esac
fi
exit $ERR_STD_MISUSE 
}

usage_commands(){

	UNK_CMD=$1
	
	echo "WORKER: Unknown command '$UNK_CMD'"
	echo
	echo "Worker commands are:"
	echo "   start       Start OurGrid worker"
	echo "   restart     Stop and start OurGrid worker"
	echo "	stop        Stop OurGrid worker"
	echo "	status      Verify OurGrid worker"
	echo "	gui         Start Worker's GUI"
}

	#-------MAIN-------#
	so=`uname`
	case $so in
		FreeBSD)
			GM=`hostname`
			;;
		*)
			GM=`hostname -f`
			;;
	esac
	nargs=$#
	
	if [ $nargs -eq 1 ]; then
		COMMAND_NAME=$1
	
		if 	[ "$COMMAND_NAME" = "start" ] || 
		[ "$COMMAND_NAME" = "gui" ] || 
		[ "$COMMAND_NAME" = "stop" ] || 
		[ "$COMMAND_NAME" = "status" ] || 
		[ "$COMMAND_NAME" = "restart" ]; then

		array=$(ls /etc/ourgrid/)
                    count=0
                    for i in $array
                    do
                        if [ -f "/etc/ourgrid/$i/worker.properties" ]; then
                                count=$((count+1))
                        fi
                    done

                    for ((c=1; c<=$count; c++))
                    do
                        case "$COMMAND_NAME" in
                            start)
                                /etc/ourgrid/bin/worker-core start $c
                                ;;
                            status)
                                /etc/ourgrid/bin/worker-core status $c
                                ;;
                            stop)
                                /etc/ourgrid/bin/worker-core stop $c
                                ;;
                            restart)
                                /etc/ourgrid/bin/worker-core restart $c
                                ;;
                            gui)
                                /etc/ourgrid/bin/worker-core gui $c
                                ;;
                            *) usage
                        esac
                    done	
			
		else
			usage
		fi
		
	else 
		if [ $nargs -eq 0 ]; then
			usage
		fi
		
		if [ $nargs -eq 2 ]; then
			COMMAND_NAME=$1
			INDEX=$2
	
			if 	[ "$COMMAND_NAME" != "start" ] && 
				[ "$COMMAND_NAME" != "gui" ] && 
				[ "$COMMAND_NAME" != "stop" ] && 
				[ "$COMMAND_NAME" != "status" ] && 
				[ "$COMMAND_NAME" != "restart" ]; then
				
				usage
			fi
			
			
			
			if echo "$INDEX" | egrep -q '^[0-9]+$'; then
			
				case "$COMMAND_NAME" in
				start)
					 /etc/ourgrid/bin/worker-core start $INDEX
					;;
				status)
					/etc/ourgrid/bin/worker-core status $INDEX
					;;
				stop)
					/etc/ourgrid/bin/worker-core stop $INDEX
					;;
				restart)
					/etc/ourgrid/bin/worker-core restart $INDEX 
					;;
				gui)
					/etc/ourgrid/bin/worker-core gui $INDEX
					;;
				*) usage
				esac
			
				exit $ret			
			else
				usage
			fi
		fi
	fi