#! /bin/sh

# chkconfig: 016 20 95
# description: Stops ourgrid-peer
# processname: peer-stop

### BEGIN INIT INFO
# Provides:          peer
# Required-Stop:     $remote_fs $syslog
# Default-Stop:      0 1 6
# Short-Description: Stops the peer module of OurGrid(ourgrid.org)
### END INIT INFO

su ourgrid -c "peer stop" &> /dev/null