#! /bin/sh

# chkconfig: 2345 95 20
# description: Starts ourgrid-peer
# processname: peer-start

### BEGIN INIT INFO
# Provides:          peer
# Required-Start:    $remote_fs $syslog
# Default-Start:     2 3 4 5
# Short-Description: Starts the peer module of OurGrid(ourgrid.org)
### END INIT INFO

su ourgrid -c "peer start" &> /dev/null