#! /bin/sh

# chkconfig: 016 20 95
# description: Stops ourgrid-ds
# processname: ds-stop

### BEGIN INIT INFO
# Provides:          ds
# Required-Stop:     $remote_fs $syslog
# Default-Stop:      0 1 6
# Short-Description: Stops the ds module of OurGrid(ourgrid.org)
### END INIT INFO

#sudo -u ourgrid /usr/bin/ds stop
su ourgrid -c "worker ds" &> /dev/null