#!/bin/bash
# Source debconf library.
. /usr/share/debconf/confmodule

db_get ${package.name}/username
USERNAME=$(hostname)
db_get ${package.name}/servername
SERVERNAME="xmpp.ourgrid.org"
db_get ${package.name}/dsusername
DSUSERNAME="lsd-ds"
db_get ${package.name}/dsservername
DSSERVERNAME="xmpp.ourgrid.org"
db_get ${package.name}/password
PASSWORD="xmpp-password"

PROPERTIES_FILE=/etc/ourgrid/aggregator/aggregator.properties

sed -i 's/{username}/'$USERNAME'/g' $PROPERTIES_FILE
sed -i 's/{servername}/'$SERVERNAME'/g' $PROPERTIES_FILE
sed -i 's/{password}/'$PASSWORD'/g' $PROPERTIES_FILE
sed -i 's/{ds-username}/'$DSUSERNAME'/g' $PROPERTIES_FILE
sed -i 's/{ds-servername}/'$DSSERVERNAME'/g' $PROPERTIES_FILE

CERTIFICATE_FILE=/etc/ourgrid/aggregator/certification/mycertificate/mycertificate.cer
mkdir -p /etc/ourgrid/aggregator/certification/mycertificate/
CERTIFICATE_KEYS=$(java -Djava.ext.dirs=/usr/lib/ourgrid/ org.ourgrid.common.util.SelfSignedSetup $USERNAME $SERVERNAME $CERTIFICATE_FILE)
AGGREGATOR_PUBLICKEY=$(echo $CERTIFICATE_KEYS | cut -d' ' -f1)
AGGREGATOR_PRIVATEKEY=$(echo $CERTIFICATE_KEYS | cut -d' ' -f2)
echo "" >> $PROPERTIES_FILE
echo "commune.privatekey="$AGGREGATOR_PRIVATEKEY >> $PROPERTIES_FILE
echo "commune.publickey="$AGGREGATOR_PUBLICKEY >> $PROPERTIES_FILE
echo "commune.certification.file.mycertificatefilepath="$CERTIFICATE_FILE >> $PROPERTIES_FILE

chmod +x /etc/init.d/aggregator
update-rc.d aggregator defaults


chown ourgrid /usr/bin/aggregator
chown ourgrid /usr/share/ourgrid
chown -R ourgrid /etc/ourgrid

db_purge